name: robust-steerability
channels:
  - conda-forge
dependencies:
  - python=3.11
  - h5py
  - ipykernel
  - joblib
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip:
      - -e .
      - accelerate
      - bitsandbytes
      - datasets==4.4.2
      - huggingface-hub
      - protobuf
      - sentencepiece
      - torch==2.9.1
      - transformers==4.57.1
